// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80C3XgwIJUJAsz-eEY5rHqWNSrnYmRDM',
    appId: '1:1080113242483:web:a94b45b8da333641f8e506',
    messagingSenderId: '1080113242483',
    projectId: 'flutter-firebase-query-f38c1',
    authDomain: 'flutter-firebase-query-f38c1.firebaseapp.com',
    storageBucket: 'flutter-firebase-query-f38c1.firebasestorage.app',
    measurementId: 'G-KT25FE2V8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADl0zEMn_niIUx0yfSBLbwubSuU2Bwx-c',
    appId: '1:1080113242483:android:ce89006a5a57ec4af8e506',
    messagingSenderId: '1080113242483',
    projectId: 'flutter-firebase-query-f38c1',
    storageBucket: 'flutter-firebase-query-f38c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbj2GJxxKg7xjrxZI1F1Nn3Ca2eb5X2S8',
    appId: '1:1080113242483:ios:df000537830ddbbbf8e506',
    messagingSenderId: '1080113242483',
    projectId: 'flutter-firebase-query-f38c1',
    storageBucket: 'flutter-firebase-query-f38c1.firebasestorage.app',
    iosBundleId: 'com.saminironside.regenie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbj2GJxxKg7xjrxZI1F1Nn3Ca2eb5X2S8',
    appId: '1:1080113242483:ios:df000537830ddbbbf8e506',
    messagingSenderId: '1080113242483',
    projectId: 'flutter-firebase-query-f38c1',
    storageBucket: 'flutter-firebase-query-f38c1.firebasestorage.app',
    iosBundleId: 'com.saminironside.regenie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA80C3XgwIJUJAsz-eEY5rHqWNSrnYmRDM',
    appId: '1:1080113242483:web:af338cc1bd74c70cf8e506',
    messagingSenderId: '1080113242483',
    projectId: 'flutter-firebase-query-f38c1',
    authDomain: 'flutter-firebase-query-f38c1.firebaseapp.com',
    storageBucket: 'flutter-firebase-query-f38c1.firebasestorage.app',
    measurementId: 'G-NBWXKG3SL9',
  );
}
